language: cpp

addons:
    apt:
        sources: &default_sources
            - boost-latest
        packages: &default_packages
            - libboost-all-dev

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - *default_sources
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - *default_packages
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
    - VERBOSE=ON make
